Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

Resources:
  trackifydynamodb:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for trackify-dynamodb'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-trackify-dynamodb
      AttributeDefinitions:
        - AttributeName: pallets
          AttributeType: "S"
        - AttributeName: items
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pallets
          KeyType: HASH
        - AttributeName: items
          KeyType: RANGE

Outputs:
  trackifydynamodbName:
    Description: "The name of this DynamoDB table."
    Value: !Ref trackifydynamodb
    Export: 
      Name: !Sub ${App}-${Env}-trackifydynamodbTableName
  trackifydynamodbDynamoDBTableARN:
    Description: "The ARN of the trackify-dynamodb DynamoDB table."
    Value: !GetAtt trackifydynamodb.Arn
    Export: 
      Name: !Sub ${App}-${Env}-trackifydynamodbTableArn
